"use client";

import { useEffect, useState } from "react";
import { createCoupon, deleteCoupon, getAuditLogs, getCoupons, getCustomers, getModerationReviews, getSupportTickets, importProducts, moderateReview, updateCoupon, updateCustomer, updateSupportTicket } from "@/services/admin";

const Section = ({ title, children }) => <section className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>;

export default function ManageStore() {
  const [data,setData]=useState({coupons:[],reviews:[],customers:[],tickets:[],audits:[]}); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const load=async()=>{try{const [c,r,u,t,a]=await Promise.all([getCoupons(),getModerationReviews(),getCustomers(),getSupportTickets(),getAuditLogs()]);setData({coupons:c.data?.data??c.data??[],reviews:r.data?.data??r.data??[],customers:u.data??[],tickets:t.data?.data??t.data??[],audits:a.data?.data??a.data??[]});}catch(e){setError(e.message);}};
  useEffect(()=>{load();},[]);
  const addCoupon=async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await createCoupon({code:f.get("code"),percentOff:Number(f.get("percentOff")),active:true,expiresAt:f.get("expiresAt")||null});e.currentTarget.reset();setMessage("Coupon created.");load();}catch(err){setError(err.message);}};
  const uploadCsv=async(e)=>{const file=e.target.files?.[0];if(!file)return;try{const result=await importProducts(file);setMessage(`${result.created} products created; ${result.updated} updated.`);}catch(err){setError(err.message);}e.target.value="";};
  return <div className="space-y-6 p-4 md:p-10"><header><h1 className="text-2xl font-semibold">Store administration</h1><p className="text-gray-500">Catalogue operations, customers, moderation, support, and accountability.</p></header>{error?<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>:null}{message?<p role="status" className="rounded bg-green-50 p-3 text-green-700">{message}</p>:null}
    <div className="grid gap-6 xl:grid-cols-2"><Section title="Coupons"><form onSubmit={addCoupon} className="mb-4 grid grid-cols-3 gap-2"><input name="code" required placeholder="CODE" className="rounded border p-2"/><input name="percentOff" required type="number" min="1" max="100" placeholder="% off" className="rounded border p-2"/><input name="expiresAt" type="date" className="rounded border p-2"/><button className="col-span-3 rounded bg-orange-600 p-2 text-white">Create coupon</button></form>{data.coupons.map(c=><div key={c.id} className="flex items-center justify-between border-t py-2"><p><strong>{c.code}</strong> — {c.percent_off}% {c.active?"active":"inactive"}</p><div className="flex gap-2"><button onClick={()=>updateCoupon(c.id,{code:c.code,percentOff:c.percent_off,active:!c.active,expiresAt:c.expires_at}).then(load)} className="text-blue-700">{c.active?"Disable":"Enable"}</button><button onClick={()=>deleteCoupon(c.id).then(load)} className="text-red-700">Delete</button></div></div>)}</Section>
    <Section title="Bulk product import"><p className="mb-3 text-sm text-gray-600">CSV columns: sku, name, description, category_id, price, offer_price, stock_quantity.</p><label className="block cursor-pointer rounded border-2 border-dashed p-8 text-center"><input type="file" accept=".csv,text/csv" onChange={uploadCsv} className="sr-only"/>Choose CSV file</label></Section>
    <Section title="Review moderation"><div className="max-h-80 space-y-3 overflow-auto">{data.reviews.map(r=><article key={r.id} className="rounded border p-3"><p>{"★".repeat(r.rating)} — {r.comment}</p><p className="text-xs text-gray-500">{r.user?.name} · {r.status}</p>{r.status==="pending"?<div className="mt-2 flex gap-2"><button onClick={()=>moderateReview(r.id,"approved").then(load)} className="rounded bg-green-600 px-2 py-1 text-white">Approve</button><button onClick={()=>moderateReview(r.id,"rejected").then(load)} className="rounded bg-red-600 px-2 py-1 text-white">Reject</button></div>:null}</article>)}</div></Section>
    <Section title="Customer and employee management"><div className="max-h-80 overflow-auto">{data.customers.map(u=><div key={u.id} className="border-t py-2"><strong>{u.name}</strong><p className="text-sm text-gray-500">{u.email} · {u.roleType} · {u.loyaltyPoints} points · ${u.storeCredit} credit</p><div className="mt-1 flex gap-3 text-sm">{u.roleType==="Customer"?<button className="text-blue-700" onClick={()=>{const value=prompt("New store credit balance",u.storeCredit);if(value!==null)updateCustomer(u.id,{storeCredit:Number(value)}).then(load);}}>Adjust credit</button>:null}{u.roleType==="Employee"?<button className="text-blue-700" onClick={()=>{const value=prompt("Comma-separated permissions",(u.permissions??[]).join(","));if(value!==null)updateCustomer(u.id,{permissions:value.split(",").map(v=>v.trim()).filter(Boolean)}).then(load);}}>Edit permissions</button>:null}</div></div>)}</div></Section>
    <Section title="Support tickets"><div className="max-h-80 space-y-3 overflow-auto">{data.tickets.map(t=><article key={t.id} className="rounded border p-3"><strong>#{t.id} {t.subject}</strong><p className="text-sm">{t.message}</p><p className="text-xs text-gray-500">{t.status} · {t.priority}</p>{!['resolved','closed'].includes(t.status)?<button onClick={()=>updateSupportTicket(t.id,{status:"resolved",adminResponse:"Resolved by support."}).then(load)} className="mt-2 rounded bg-blue-600 px-2 py-1 text-white">Resolve</button>:null}</article>)}</div></Section>
    <Section title="Administrative audit log"><div className="max-h-80 overflow-auto text-sm">{data.audits.map(a=><div key={a.id} className="border-t py-2"><strong>{a.method}</strong> {a.path}<p className="text-xs text-gray-500">{a.user?.name??"System"} · HTTP {a.status_code} · {new Date(a.created_at).toLocaleString()}</p></div>)}</div></Section></div>
  </div>;
}
