"use client";

import { useEffect, useState } from "react";
import Footer from "@/components/Footer"; import Navbar from "@/components/Navbar";
import { useAppContext } from "@/context/AppContext";
import { changePassword, createTicket, deleteAccount, getLoginHistory, getSessions, getTickets, revokeSession, sendVerification, updateAccount } from "@/services/account";
import { deleteAddress, patchAddress, postAddress } from "@/services/address";

const Card = ({ title, children }) => <section className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>;
const field = "w-full rounded border px-3 py-2";

export default function ProfilePage() {
  const { userData, fetchUserData, logout, router } = useAppContext(); const [sessions, setSessions] = useState([]); const [history, setHistory] = useState([]); const [tickets, setTickets] = useState([]); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = async () => { if (!userData) return; try { const [s, h, t] = await Promise.all([getSessions(), getLoginHistory(), getTickets()]); setSessions(s.data); setHistory(h.data); setTickets(t.data?.data ?? t.data ?? []); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, [userData?.id]);
  const run = async (action, message) => { try { setError(""); await action(); setNotice(message); await fetchUserData(); await load(); } catch (e) { setError(e.message); } };
  if (!userData) return <><Navbar /><main className="min-h-screen p-10">Sign in to manage your account.</main><Footer /></>;
  return <><Navbar /><main className="mx-auto min-h-screen max-w-6xl space-y-6 px-4 py-10"><header><h1 className="text-3xl font-semibold">Account</h1><p className="text-gray-500">Profile, delivery, security, preferences, rewards, and support.</p></header>{error ? <p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p> : null}{notice ? <p role="status" className="rounded bg-green-50 p-3 text-green-700">{notice}</p> : null}
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Profile"><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => updateAccount({ name: f.get('name'), email: f.get('email'), phone: f.get('phone') }), "Profile saved."); }} className="space-y-3"><input className={field} name="name" defaultValue={userData.name} required /><input className={field} name="email" type="email" defaultValue={userData.email} required /><input className={field} name="phone" defaultValue={userData.phone ?? ""} placeholder="Phone" /><button className="rounded bg-orange-600 px-4 py-2 text-white">Save profile</button></form><div className="mt-4 border-t pt-4"><p className={userData.emailVerifiedAt ? "text-green-700" : "text-amber-700"}>{userData.emailVerifiedAt ? "Email verified" : "Email not verified"}</p>{!userData.emailVerifiedAt ? <button onClick={() => run(sendVerification, "Verification email sent.")} className="mt-2 text-blue-700 underline">Send verification link</button> : null}</div></Card>
      <Card title="Rewards"><div className="grid grid-cols-2 gap-4"><div className="rounded bg-orange-50 p-4"><p className="text-sm">Loyalty points</p><strong className="text-2xl">{userData.loyaltyPoints}</strong></div><div className="rounded bg-green-50 p-4"><p className="text-sm">Store credit</p><strong className="text-2xl">${userData.storeCredit}</strong></div></div><p className="mt-4 text-sm">Referral code: <strong className="select-all">{userData.referralCode}</strong></p></Card>
      <Card title="Saved delivery addresses"><div className="space-y-3">{userData.addresses?.map(a => <article key={a.id} className={`rounded border p-3 ${a.isDefault ? 'border-orange-500 bg-orange-50' : ''}`}><div className="flex justify-between"><strong>{a.fullName}</strong>{a.isDefault ? <span className="text-sm text-orange-700">Default</span> : null}</div><p className="text-sm text-gray-600">{a.streetName}, {a.suburb}, {a.city}, {a.country} {a.postalCode}</p><div className="mt-2 flex gap-3 text-sm">{!a.isDefault ? <button className="text-blue-700" onClick={() => run(() => patchAddress(a.id, { isDefault: true }), "Default address updated.")}>Make default</button> : null}<button className="text-red-700" onClick={() => run(() => deleteAddress(a.id), "Address deleted.")}>Delete</button></div></article>)}</div><form onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); run(() => postAddress(f), "Address added."); e.currentTarget.reset(); }} className="mt-4 grid grid-cols-2 gap-2"><input className={field} name="fullName" placeholder="Full name" required /><input className={field} name="streetName" placeholder="Street" required /><input className={field} name="suburb" placeholder="Suburb" required /><input className={field} name="city" placeholder="City" required /><input className={field} name="country" placeholder="Country" required /><input className={field} name="postalCode" placeholder="Postal code" required /><button className="col-span-2 rounded border p-2">Add address</button></form></Card>
      <Card title="Notifications"><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); run(() => updateAccount({ notificationPreferences: { orders: f.has('orders'), promotions: f.has('promotions'), support: f.has('support') } }), "Preferences saved."); }} className="space-y-3">{['orders', 'promotions', 'support'].map(k => <label key={k} className="flex gap-2 capitalize"><input type="checkbox" name={k} defaultChecked={userData.notificationPreferences?.[k]} />{k} emails</label>)}<button className="rounded border px-4 py-2">Save preferences</button></form></Card>
      <Card title="Password"><form onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); run(() => changePassword(f), "Password changed."); e.currentTarget.reset(); }} className="space-y-2"><input className={field} name="currentPassword" type="password" placeholder="Current password" required /><input className={field} name="password" type="password" placeholder="New password" required /><input className={field} name="password_confirmation" type="password" placeholder="Confirm new password" required /><button className="rounded border px-4 py-2">Change password</button></form></Card>
      <Card title="Active sessions"><div className="space-y-2">{sessions.map(s => <div key={s.id} className="flex justify-between border-t py-2 text-sm"><span>{s.name} {s.current ? '(this session)' : ''}<small className="block text-gray-500">{s.lastUsedAt ? new Date(s.lastUsedAt).toLocaleString() : 'Not used yet'}</small></span>{!s.current ? <button onClick={() => run(() => revokeSession(s.id), "Session revoked.")} className="text-red-700">Revoke</button> : null}</div>)}</div><h3 className="mt-5 font-medium">Recent logins</h3>{history.slice(0, 5).map(h => <p key={h.id} className="mt-2 text-xs text-gray-500">{new Date(h.loggedInAt).toLocaleString()} · {h.ipAddress} · {h.userAgent}</p>)}</Card>
      <Card title="Customer support"><form onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); run(() => createTicket(f), "Support ticket created."); e.currentTarget.reset(); }} className="space-y-2"><input className={field} name="subject" placeholder="Subject" required /><textarea className={field} name="message" placeholder="How can we help?" required /><button className="rounded bg-blue-600 px-4 py-2 text-white">Create ticket</button></form>{tickets.map(t => <div key={t.id} className="mt-3 border-t pt-3 text-sm"><strong>#{t.id} {t.subject}</strong><p>{t.status} · {t.admin_response ?? "Awaiting response"}</p></div>)}</Card>
      <Card title="Delete account"><p className="mb-3 text-sm text-gray-600">This permanently removes your profile and signs out every session.</p><form onSubmit={e => { e.preventDefault(); const password = new FormData(e.currentTarget).get('password'); if (confirm('Permanently delete this account?')) run(() => deleteAccount(password).then(() => { localStorage.removeItem('token'); router.push('/'); }), "Account deleted."); }} className="flex gap-2"><input className={field} name="password" type="password" placeholder="Confirm password" required /><button className="rounded bg-red-700 px-4 text-white">Delete</button></form></Card></div>
    <button onClick={logout} className="rounded border px-4 py-2">Sign out</button></main><Footer /></>;
}
