"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Footer from "@/components/Footer"; import Loading from "@/components/Loading"; import Navbar from "@/components/Navbar"; import OrderItems from "@/components/OrderItems";
import { useAppContext } from "@/context/AppContext"; import { getOrder } from "@/services/order";
import {cancelOrder,downloadOrderDocument,reorder,requestReturn} from "@/services/shopping";

export default function OrderDetail(){
 const {id}=useParams();const {currency,setCartItems,router}=useAppContext();const [order,setOrder]=useState(null);const [error,setError]=useState("");
 useEffect(()=>{let active=true;getOrder(id).then(r=>active&&setOrder(r.data)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[id]);
 return <><Navbar/><main className="min-h-screen px-6 py-12 md:px-16 lg:px-32">{!order&&!error?<Loading/>:null}{error?<p className="rounded bg-red-50 p-4 text-red-700">{error}</p>:null}{order?<article className="mx-auto max-w-4xl rounded-xl border bg-white p-6 shadow-sm">
  <header className="mb-6 flex flex-wrap justify-between gap-4"><div><p className="text-sm text-gray-500">Placed {new Date(order.placedAt).toLocaleString()}</p><h1 className="text-2xl font-semibold">Order #{order.id}</h1></div><div className="text-right"><p className="capitalize font-medium text-orange-700">{order.fulfillmentStatus}</p><p className="text-sm capitalize text-gray-500">Payment: {order.paymentStatus} · {order.paymentMethod.replaceAll("_"," ")}</p></div></header>
  <OrderItems items={order.items} currency={currency}/><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>reorder(order.id).then(r=>{setCartItems(r.data);router.push('/cart');})} className="rounded border px-3 py-2">Buy again</button><button onClick={()=>downloadOrderDocument(order.id)} className="rounded border px-3 py-2">Download invoice</button>{order.paymentStatus==='unpaid'&&order.fulfillmentStatus==='unfulfilled'?<button onClick={()=>cancelOrder(order.id).then(()=>location.reload())} className="rounded border border-red-600 px-3 py-2 text-red-700">Cancel order</button>:null}</div>
  {order.fulfillmentStatus==='delivered'?<section className="mt-5 rounded bg-gray-50 p-4"><h2 className="font-semibold">Request a return</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);requestReturn(order.id,f).then(()=>location.reload());}} className="mt-3 grid gap-2 md:grid-cols-2"><select name="orderItemId" className="border p-2">{order.items.map(i=><option key={i.id} value={i.id}>{i.productName}</option>)}</select><input name="quantity" type="number" min="1" defaultValue="1" className="border p-2"/><select name="reason" className="border p-2"><option value="damaged">Damaged</option><option value="wrong_item">Wrong item</option><option value="not_as_described">Not as described</option><option value="changed_mind">Changed mind</option><option value="other">Other</option></select><input name="evidence" type="file" accept="image/*" className="border p-2"/><textarea name="details" placeholder="Details" className="border p-2 md:col-span-2"/><button className="rounded bg-orange-600 p-2 text-white md:col-span-2">Submit return</button></form></section>:null}
  <section className="mt-6 border-t pt-5"><h2 className="font-semibold">Order activity</h2><ol className="mt-3 space-y-3">{order.activity?.map(event=><li key={event.id} className="border-l-2 border-orange-400 pl-4"><p className="font-medium">{event.description}</p><time className="text-xs text-gray-500">{new Date(event.createdAt).toLocaleString()}</time></li>)}</ol></section>
  {order.shipments?.map(shipment=><section key={shipment.id} className="mt-6 border-t pt-5"><h2 className="font-semibold">Tracking: {shipment.carrier} {shipment.trackingNumber}</h2><ol className="mt-3 space-y-2">{shipment.events.map(event=><li key={event.id}><strong className="capitalize">{event.status.replaceAll('_',' ')}</strong> · {event.description} {event.location?`· ${event.location}`:''}<time className="block text-xs text-gray-500">{new Date(event.occurredAt).toLocaleString()}</time></li>)}</ol></section>)}
  <div className="mt-6 grid gap-5 border-t pt-5 md:grid-cols-2"><address className="not-italic text-sm text-gray-600"><strong className="text-gray-900">Ship to</strong><p>{order.address?.fullName}<br/>{order.address?.streetName}, {order.address?.suburb}<br/>{order.address?.city}, {order.address?.country} {order.address?.postalCode}</p></address><div className="text-right"><p>Subtotal: {currency}{order.subtotal}</p>{Number(order.discountTotal)>0?<p>Discount: -{currency}{order.discountTotal}</p>:null}<p className="text-xl font-semibold">Total: {currency}{order.total}</p></div></div>
 </article>:null}</main><Footer/></>;
}
